config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'

  get '/home/by_author/', :to=>"home#by_author"

  resources :books
  resources :authors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :author

	def self.get_books_by_author(author_id)
		self.where("author_id=?", author_id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :age, :latest_book)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :based_on, :publish_date, :author_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@all_books = Book.all
	end

	def by_author
		@books_by_author = Book.get_books_by_author(params[:author_id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      
      <%= form_with(model: author, local: true) do |form| %>
        <% if author.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

            <ul>
            <% author.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, id: :author_id, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :age %>
          <%= form.text_field :age, id: :author_age, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :latest_book %>
          <%= form.text_field :latest_book, id: :author_latest_book, class: 'form-control' %>
        </div>

        <div class="actions">
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="row">
  <div class="col-md-12">
    <h1 class="text-center">Authors</h1><br/>
    <table class="table table-bordered">

      <thead class="text-center">
        <tr>
          <th>Name</th>
          <th>Age</th>
          <th>Latest book</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @authors.each do |author| %>
          <tr class="text-center">
            <td><%= author.name %></td>
            <td><%= author.age %></td>
            <td><%= author.latest_book %></td>
            <td class="text-center"><%= link_to 'Show', author %> | 
            <%= link_to 'Edit', edit_author_path(author) %> | 
            <%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Author', new_author_path, class:'btn btn-success' %>
  </div>
</div>  


</div>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<div class="container">
	
	<p id="notice"><%= notice %></p>
<div class="container">
	<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

  <p>
  <strong>Age:</strong>
  <%= @author.age %>
</p>

<p>
  <strong>Latest book:</strong>
  <%= @author.latest_book %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :book_name %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%#= form.text_field :author_id, id: :author_id %>
    <%= form.select :author_id, Author.all.collect {|t| [t.name, t.id]}, {prompt: '-- Select Author Name --'}, class: 'form-control' %>

  </div>

  <div class="field">
    <%= form.label :based_on %>
    <%= form.text_field :based_on, id: :book_based_on %>
  </div>

  <div class="field">
    <%= form.label :publish_date %>
    <%= form.text_field :publish_date, id: :book_publish_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>


   <div class="container">
       <%= render 'form', book: @book %>

        <%= link_to 'Show', @book %> |
        <%= link_to 'Back', books_path %>
	

</div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Books</h1>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Author Name</th>
        <th>Based on</th>
        <th>Publish date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.name %></td>
          <td><%= book.author.name %></td>
          <td><%= book.based_on %></td>
          <td><%= book.publish_date %></td>
          <td><%= link_to 'Show', book %></td>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Book', new_book_path, class:'btn btn-success' %>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author Name:</strong>
  <%= @book.author_id %>
</p>

<p>
  <strong>Based on:</strong>
  <%= @book.based_on %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @book.publish_date %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>
	

</div>

app/views/home/by_author.html.erb
<% @books_by_author.each do |boo| %>
  <%= boo.name %><br/>
<% end %>

app/views/home/index.html.erb
<div class="container" style="margin-top: 150px;">

  
  <!-- <h2>List of Books</h2> -->
  <!-- <ul class="list-group">
  	<%# @all_books.each do |book| %>
  		<li class="list-group-item">
  			<%#= link_to book.name, book_path(book.id) %><br/>
  		</li>
	<%# end %>
   
  </ul> -->
  <div class="row text-center">
        <div class="col-lg-6 col-md-offset-3">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Authors</h4>
              <!-- <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p> -->
              <a href="/authors" class="btn btn-primary">View All</a>
            </div>
          </div>
        </div>

        <div class="col-lg-6 col-md-offset-3">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Books</h4>
              <!-- <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo magni sapiente, tempore debitis beatae culpa natus architecto.</p> -->
              <a href="/books" class="btn btn-primary">View All</a>
            </div>
          </div>
        </div>

      </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

   
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>

  	<%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/">Library</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/authors">Authors</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/books">Books</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>